name: Publish
run-name: Publish

on: workflow_dispatch

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get version
        run: |
          version=$(npm pkg get version | xargs)
          echo "TAG=${version}" >> $GITHUB_ENV

      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.TAG }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: create-tag

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: Build Package
        run: |
          npm ci
          npm run build
          cd dist
          mv parse-mediawiki-template.umd.cjs parse-mediawiki-template-min.js

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
