name: Run Tests
run-name: Run Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Test Build
        run: npm run build

      - name: Run Tests
        run: npm run test
